- id: automate_functions
  name: Add functions to mkgendocs configurations YAML
  entry: bash -c "python3 gendoc.py; git add -u" --
  language: system
- id: mkgendocs
  name: Generate markdown from docstrings
  entry: bash -c "gendocs --config 'mkgendocs.yml'; git add -u" --
  language: system
- id: mkbuild
  name: Build the markdown documentation, run with '$ mkdocs serve' at http://127.0.0.1:8000/
  entry: bash -c 'mkdocs build'
  language: system
