# This is an instance of a config TOML for pear
# Compute distances > method: hashrf
# Compute embedding > method: pca - dimensions: 3
# Plot embedding > method: pca - dimensions: 3 -

title = "TOML Example"

[trees]
file = "Pear-EBI/examples_tree_sets/MAPLE_res/sim_MAPLE_intermediateTrees.tree_clean"
# output_file = None
# distance_matrix = None
# metadata = None

[distance]
method = "hashrf"

[embedding]
method = "pca"
dimensions = 3
quality = true

[plot]
method = "pca"
save = false
# name_plot = None
static = false
plot_meta = "SET-ID"
# plot_set = None
select = false
same_scale = false
