[trees]
file1 = "../MAPLE_res/IQtreeStartingTree_Trees"
file2 = "../MAPLE_res/ParsimonyRAxMLStartingTree_GTRmodel_Trees"
file3 = "../MAPLE_res/RAxMLNGStartingTree_Trees"
file4 = "../MAPLE_res/UshERStartingTree_Trees"

[collection]
distance_matrix = "../MAPLE_res/smart_RF_DistMat_Maple.csv"
metadata = "../MAPLE_res/Likelihoods.csv"

[embedding]
method = "pcoa"
dimensions = 3

[plot]
plot_meta = "LK"
z_axis = "LK"
select = false
same_scale = true
show = true
